language: julia
os:
    - linux
    - osx
    - windows
julia:
    - 1.3
    - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
    email: false
sudo: false
after_success:
    - julia -e 'cd(Pkg.dir("Gumbo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
