language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Gumbo"); Pkg.test("Gumbo"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("Gumbo")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
